### ISSUE TITLE
Issue with multiple Matrix

### ISSUE THREAD

**Issue by Jag907** [AaronLiddiment/RGBLEDS#15]
Hi Aaron,
I am using a mega 2560 and  4  16x16 WS2812B matrix displays with LEDtext eg. 4 . I was getting what looked like just random pixels on the display. I switched to Horizontal Zigzag matrix, now the text is scrolling and displaying perfectly but only on 1 matrix. As soon as I increase the max width to a greater
number to use the other displays the text just falls apart it looks like its to big and scanning in different
directions over each other. Would appreciate your input on this.

Regards

Jim

**Comment by AaronLiddiment** [comment]
The Matrix class is not written to control multiple separate matrix! Think about it..... if you don't have to tell the code how wide each individual matrix is, it will be impossible for it to work correctly!
There is someone who has forked my code and added multiple matrix support but I can't remember who it is, do a git search for it.
