### ISSUE TITLE
No issue: Just question

### ISSUE THREAD

**Issue by njection** [AaronLiddiment/RGBLEDS#2]
Can you illustrate the different matrix types. I want to make sure I cut these LEDs correctly to match.

Thanks.

**Comment by AaronLiddiment** [comment]
Using my Matrix class you can wire them up anyway you want, but here are the main four types.

HORIZONTAL_ZIGZAG
789
654
123

HORIZONTAL
789
456
123

VERTICAL_ZIGZAG
349
258
167

VERTICAL
369
258
147

The most common way to wire them up is to use the ZIGZAG layout as this reduces the amount of wire used when connecting the ends of the rows or columns.
Hope this helps

**Comment by njection** [comment]
Awesome. Thanks for the quick response. One other question. Can you control the width of the pixels? The matrix I'm using in a 5 x 40. Are all the letter widths 5x5? Trying to help them come out better.

**Comment by AaronLiddiment** [comment]
I am thinking about adding proportional font support when I get some time.
At the moment every character in the font is the same width I'm afraid!
Obviously different fonts can be different widths though.

**Comment by njection** [comment]
Cool.. Can I redesign the font file.

**Comment by AaronLiddiment** [comment]
Yes, there are 3 example font header files in the LEDText folder.
For easier font design in a text editor the 'Robotron.h' is the best example as it uses a binary marco so the characters are designed using 1's and 0's.

**Comment by njection** [comment]
Last question (maybe) can I combine font header files? I may try to separate  "W" and "M" (5x5) into its own header file, and break up everything else into it's own(5x3). Is this possible or not a good idea.

**Comment by AaronLiddiment** [comment]
The Font data is a uint8_t array and only one can be used with the text routine at a time I am afraid.
The only way you could have wider characters is to use 2 character codes to define a single letter.
So for example define the left of the 'W' using 'W' and the right of the 'W' using '['. The limitation of this is that the character would then have to be twice the standard width.

**Comment by njection** [comment]
I'm having issues creating a 3 (wide) x 5 (high) font. I modded the 'Robotron.h' file but everything comes out blank. Is there anyway you could build it?

**Comment by AaronLiddiment** [comment]
I imagine you have placed yours 1's at the end of the bytes where they should be in the upper bits.
B8(11100000) not B8(00000111).
Let me know if that fixes it?

**Comment by njection** [comment]
Thanks. That fixed it.

**Comment by AaronLiddiment** [comment]
I have just added proportional font support :)
Use the "Master" branch to get it. I have included an example font "FontP16x16.h"
Basically you have to define the font as if it is the full maximum width & height, but you add an extra number at the start of each character that is the actual width. Then you just OR in the define
"FONT_PROPORTIONAL" with the width at the top of the font file.

**Comment by ghost** [comment]
Hello Aaron, thank you for the library.
I've built a 5x5 font and everything seems to be going well with one small hitch.
Everything is upside down and backward.

Not entirely unexpected as you define your horizontal matrix as such (from above):
789
456
123

While mine is built like so:
123
456
789

Seems like there should be a relatively quick fix for this.
Any thoughts?

Thanks again!

**Comment by AaronLiddiment** [comment]
Hi,
If you check my other repositories you will now notice I have split out each of the LED classes and added full Wiki's for each class. I won't be updating this RGBLEDS one anymore so any corrections/additions won't be seen here.
Anyway, a solution for your problem is easy ;)
Here is a snippet from the LEDMatrix Wiki :-

It is also possible to reverse the X and/or Y axis by using a negative (-) sign before the width/height values:-
cLEDMatrix< MATRIX_WIDTH, -MATRIX_HEIGHT, MATRIX_TYPE > leds;
In the above example this would move the Y origin to the opposite end, so would be used where the first led is at the top but you still want Y origin to be at the bottom.
