### ISSUE TITLE
Question: Draw Multi Colour Line

### ISSUE THREAD

**Issue by Delphi** [AaronLiddiment/RGBLEDS#6]
Greetings, I was wondering if there was a way to use DrawLine(int16_t x0, int16_t y0, int16_t x1, int16_t y1, CRGB Col); but with some of the same effects used for text such as SetTextColrOptions(uint16_t Options, uint8_t ColA1 = 0xff, uint8_t ColA2 = 0xff, uint8_t ColA3 = 0xff, uint8_t ColB1 = 0xff, uint8_t ColB2 = 0xff, uint8_t ColB3 = 0xff);

This would be great for drawing a line that can transition between 2 colours.

Thank You.

**Comment by AaronLiddiment** [comment]
Good idea, a bit busy at the moment, but as soon as I get a chance I will look at adding this option :)

**Comment by Delphi** [comment]
Grand, I look forward to it. :)

Many thanks.
