### ISSUE TITLE
[QUESTION] Remove gap between characters?

### ISSUE THREAD

**Issue by IAmOrion** [AaronLiddiment/RGBLEDS#9]
Could you tell me what to modify in order to remove the 1 row gape between characters when scrolling text?

As an example, I am using an 8x32 Matrix, Using CHAR_LEFT and scrolling text, my Font already has 1 blank row at row 8 of the 8 pixel font height, so I'd really like to remove the coded 1 row if poss?

**Comment by AaronLiddiment** [comment]
Why not edit the font data and remove the last '0' byte from each character as this will also have the benefit of reducing memory.
It would be possible to modify the function but at the moment I am really busy and won't get a chance to look for a few days.

**Comment by IAmOrion** [comment]
Thanks for the info, I did it a different way in the end, but removing the last 0 would have also worked
